Create an image container component #19
italanta/elewa-website pull request #122
Opened 2023-08-25 12:21 UTC by levy-web

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Reference the issue related to this PR as shown below. Every issue has it's own number you can find the issue numbers [here](https://github.com/italanta/italanta-apps/issues).

Fixes # (issue) - *Example*: Fixes #10, #20 NOTE: GitHub issue numbers should be prefixed with **#** to aid with issue tracking.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Screenshot (optional)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**: (optional)

- Firmware version:
- Hardware:
- Toolchain:
- SDK:

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-08-29 06:38 UTC, LemmyMwaura requested changes

2023-08-29 06:38 UTC, LemmyMwaura commented on libs/elements/layout/images/src/lib/components/image-container/image-container.component.ts
> +
There's no need to have this as a setter since the value will never change after it's initially passed in. We can just pass it in as input.

2023-08-29 06:38 UTC, LemmyMwaura commented on libs/elements/layout/images/src/lib/components/image-container/image-container.component.ts
> +  }
Also here, we don't need a getter.

2023-08-29 06:38 UTC, LemmyMwaura commented on libs/elements/layout/images/src/lib/components/image-container/image-container.component.ts
> +
In this method, you should make use of the imageVisualisation enum to set the class, and pass visualisation as type ImageConfig.

2023-08-29 08:52 UTC, levy-web commented
@LemmyMwaura done with the changes

2023-09-01 08:05 UTC, LemmyMwaura approved these changes

2023-09-01 08:05 UTC, merged