News item component
italanta/elewa-website pull request #123
Opened 2023-08-25 13:00 UTC by OgembaJunior

# Description

As a developer, I want a reusable news-item component that I can use to render news section texts i.e title and description for the different pages in our app.

Reference the issue related to this PR as shown below. Every issue has it's own number you can find the issue numbers [here](https://github.com/italanta/italanta-apps/issues).

Fixes #11 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Screenshot (optional)
![Screenshot from 2023-08-25 14-49-16](https://github.com/italanta/elewa-website/assets/136768250/10bb233b-0021-431a-8e77-22f22c77c16a)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**: (optional)

- Firmware version:
- Hardware:
- Toolchain:
- SDK:

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-08-28 12:57 UTC, LemmyMwaura requested changes
Your design does not match what was provided. But the structure code is good

2023-08-28 13:56 UTC, LemmyMwaura commented
Closing this as it's been merged in #87

2023-08-28 13:56 UTC, closed without merging

2023-08-29 10:20 UTC, OgembaJunior commented
So technically, it has been done by someone else


On Mon, 28 Aug 2023 at 16:56, Lemmy ***@***.***> wrote:

> Closing this as it's been merged in #87
> <https://github.com/italanta/elewa-website/pull/87>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/italanta/elewa-website/pull/123#issuecomment-1695748046>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BATOV6VESJQULLN7QPVQFJDXXSPRTANCNFSM6AAAAAA36PLPKY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-08-29 13:23 UTC, LemmyMwaura commented
@OgembaJunior 

It's been merged into the codebase.