Issue#19ft reusable image container
italanta/elewa-website pull request #138
Opened 2023-08-29 13:29 UTC by Ochieng23

# Description

Create reusable image containers

Fixes # 19

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Screenshot (optional)
![Screenshot from 2023-08-29 16-29-00](https://github.com/italanta/elewa-website/assets/44272809/a2f0d247-b188-4440-8d01-9612bee8cfa9)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**: (optional)

- Firmware version:
- Hardware:
- Toolchain:
- SDK:

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-09-01 08:54 UTC, Beulah-Matt reviewed
Good attempt.
This issue has however been resolved by PR #122

2023-09-05 07:27 UTC, LemmyMwaura requested changes

2023-09-05 07:27 UTC, LemmyMwaura commented on libs/elements/layout/images/src/lib/elewa-image-container/elewa-image-container.component.html
> +    </h2>
to add dynamic classes use ng-class directive or bind the class. interpolation doesn't work. If you were trying to just get the title then you could have achieved this directly

2023-09-05 07:27 UTC, LemmyMwaura commented on libs/features/pages/home/src/lib/main/home/home-page.component.ts
> +    {
No need to push these changes. They are just for your own viewing

2023-09-05 07:28 UTC, LemmyMwaura commented
Closing this as its already been merged, but good work

2023-09-05 07:28 UTC, closed without merging