Website footer
italanta/elewa-website pull request #144
Opened 2023-08-30 19:55 UTC by stephenonchieku1

# Description
This pr  resolve the issue of creating a  responsive and dynamic  footer  for the website

Fixes # (#135 ) 
## Type of change
- [ x] New feature (non-breaking change which adds functionality)

## Screenshot (optional)
![image](https://github.com/italanta/elewa-website/assets/110173070/9689bf84-45d9-4124-9a54-cc8629af61c6)
![image](https://github.com/italanta/elewa-website/assets/110173070/b2cad8ce-b472-48e8-a542-e0cfecb3da31)

## How Has This Been Tested?
- [x ] Test A- the component sucessfully runs and displays  as required in the design

## Checklist

- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ x] Any dependent changes have been merged and published in downstream modules

2023-08-31 08:05 UTC, Beulah-Matt requested changes
This PR seems as the first, address those changes.

2023-08-31 08:05 UTC, Beulah-Matt commented on libs/features/pages/home/src/lib/features-pages-home.module.ts
> +import { ButtonsModule } from '@elewa-website/elements/layout/buttons';
Remove comments.

2023-09-01 08:15 UTC, Beulah-Matt approved these changes
Good job.

2023-09-01 08:34 UTC, LemmyMwaura approved these changes

2023-09-01 08:35 UTC, merged