:sparkles: Creates App's website footer #135
italanta/elewa-website pull request #147
Opened 2023-08-31 06:37 UTC by dennis-mburu

# Description

This PR creates a reusable footer which allows use of dynamic content depending on which page it will be used. No new dependencies have been added.

Fixes # 135

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Screenshot 
![Screenshot from 2023-08-31 09-30-22](https://github.com/italanta/elewa-website/assets/65117575/cd363f20-b07d-4ad0-ab87-4bf2af14f931)
![Screenshot from 2023-08-31 09-30-34](https://github.com/italanta/elewa-website/assets/65117575/2e3e92ed-6347-4650-ad0f-577016ff1640)
![Screenshot from 2023-08-31 09-30-42](https://github.com/italanta/elewa-website/assets/65117575/ab907c48-bfbc-45e2-aa91-4f1e695793e7)

## How Has This Been Tested?
No test scripts added, just visual testing as illustrated on the screenshots above

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2023-08-31 13:11 UTC, Beulah-Matt requested changes
There are a lot of files here that came about by generating a module that are not needed. 
Look into that.

2023-08-31 13:11 UTC, Beulah-Matt commented on libs/data/ui/slider-button/src/lib/mock-slider-button.data.ts
> +};
This shouldn't be a module, just a ts file.

2023-08-31 18:43 UTC, dennis-mburu commented
I have removed the unnecessary files and updated my code accordingly. Kindly review @Beulah-Matt

2023-09-05 07:41 UTC, LemmyMwaura reviewed
Good job on the design. But I'm going to close this as it's already been solved

2023-09-05 07:41 UTC, LemmyMwaura commented on libs/elements/layout/footer/src/lib/components/footer/footer.component.html
> +        ></elewa-website-slider-button>
The button should have been part of the dynamic content

2023-09-05 07:41 UTC, closed without merging