:sparkles: generated team member section component
italanta/elewa-website pull request #159
Opened 2023-08-31 13:05 UTC by levy-web

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Reference the issue related to this PR as shown below. Every issue has it's own number you can find the issue numbers [here](https://github.com/italanta/italanta-apps/issues).

Fixes # (issue) - *Example*: Fixes #10, #20 NOTE: GitHub issue numbers should be prefixed with **#** to aid with issue tracking.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Screenshot (optional)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**: (optional)

- Firmware version:
- Hardware:
- Toolchain:
- SDK:

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-09-01 09:16 UTC, Beulah-Matt requested changes
Good job. Just make those changes. 
Also, your buttons are too short and close together. See if you can fix that too.

2023-09-01 09:16 UTC, Beulah-Matt commented on libs/features/pages/about/src/lib/components/team-members-section/team-members-section.component.ts
> +  highlightedTeamMembers = __highlightedTeamMembers;
Hi @levy-web 
This needs to be an input, like so: 
@Input() TeamMember: []
This way we can pass the array of teamMembers objects as inputs from the parent.

2023-09-01 09:16 UTC, Beulah-Matt commented on libs/features/pages/about/src/lib/components/team-members-section/team-members-section.component.html
> +    <p class="heading">These people make it happen</p>
Add this to translations, like the header and footer content has been done.

2023-09-01 10:30 UTC, levy-web commented
@Beulah-Matt completed the fix kindly check

2023-09-01 11:40 UTC, Beulah-Matt approved these changes
Good work. Approving this.

2023-09-02 12:40 UTC, LemmyMwaura approved these changes

2023-09-04 08:12 UTC, merged