Reusable pricing list component #141
italanta/elewa-website pull request #166
Opened 2023-09-01 09:57 UTC by PerisOduol618

# Description
A Reusable Pricing List Component.

Reference the issue related to this PR as shown below. Every issue has it's own number you can find the issue numbers [here](https://github.com/italanta/elewa-website/issues/141).

Fixes # (issue) - *Example*: Fixes #141  NOTE: GitHub issue numbers should be prefixed with **#** to aid with issue tracking.

## Type of change

- [ ✔️] New feature (non-breaking change which adds functionality)

## Screenshot (optional)
Screen Responsive
![Screenshot from 2023-09-01 12-26-52](https://github.com/italanta/elewa-website/assets/67086872/a3543128-ec4a-4ab1-97c6-32acbfd29720)
Phone and Tablet Responsive
![Screenshot from 2023-09-01 12-26-23](https://github.com/italanta/elewa-website/assets/67086872/b2e6d802-f928-4ca7-86ef-8f59a60f8c06)

## Checklist

- [ ✔️ ]The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
- [ ✔️ ] The code is isolated to the libs/elements/layout/cards package unless a justified reason is specified.
- [ ✔️ ] The design is responsive for screen, tablet and phone
-  [ ✔️ ]A separate commit is used for each small change
- [ ✔️ ]The commits and PR are well formatted/use proper documentation
- [ ✔️ ]The module exports the component

2023-09-01 12:16 UTC, Beulah-Matt requested changes
Hi @PerisOduol618 good job so far. 

Make the small change and tag me when you are through

2023-09-01 12:16 UTC, Beulah-Matt commented on libs/elements/cards/src/lib/components/elewa-price-list/elewa-price-list.component.ts
> +  highlightedPricingList:PriceItem[] = __highlightedPricingList;
Make this an input.

2023-09-07 09:06 UTC, PerisOduol618 commented on libs/elements/cards/src/lib/components/elewa-price-list/elewa-price-list.component.ts
> +  highlightedPricingList:PriceItem[] = __highlightedPricingList;
@Beulah-Matt I'm Done

2023-09-08 09:13 UTC, LemmyMwaura commented on libs/elements/cards/src/lib/components/elewa-price-list/elewa-price-list.component.ts
> +
Since this is a reusable component there's no need to initialise with the mockData. whatever component reuses this component will pass the mockData.

2023-09-08 12:02 UTC, LemmyMwaura commented
Clean work but i've gone with PR #197 as that is more cleaner when considering responsiveness.

2023-09-11 05:54 UTC, closed without merging