Create content development hero section #156
italanta/elewa-website pull request #172
Opened 2023-09-01 13:04 UTC by levy-web

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Reference the issue related to this PR as shown below. Every issue has it's own number you can find the issue numbers [here](https://github.com/italanta/italanta-apps/issues).

Fixes # (issue) - *Example*: Fixes #10, #20 NOTE: GitHub issue numbers should be prefixed with **#** to aid with issue tracking.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Screenshot (optional)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**: (optional)

- Firmware version:
- Hardware:
- Toolchain:
- SDK:

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-09-01 13:31 UTC, Beulah-Matt requested changes
Attach your screenshots and update the PR accordingly

2023-09-02 09:14 UTC, levy-web commented
Hi @Beulah-Matt I have updated the PR

2023-09-07 06:34 UTC, AnnaL001 commented on libs/features/pages/content-development/src/lib/components/content-dev-hero-section/content-dev-hero-section.component.scss
> +    background-color: #F2CF73;
For color/background color styling, ensure the use of CSS variables
```
background-color: var(--elewa-website-hero-section-background-color);
```

2023-09-07 06:35 UTC, AnnaL001 commented on libs/features/pages/content-development/src/lib/components/content-dev-hero-section/content-dev-hero-section.component.scss
> +    background-color: #F2CF73;
Same here

2023-09-07 06:37 UTC, AnnaL001 commented on libs/features/pages/content-development/src/lib/components/content-dev-hero-section/content-dev-hero-section.component.scss
> +    background-color: #F2CF73;
Same here

2023-09-07 06:48 UTC, AnnaL001 commented on libs/features/pages/content-development/src/lib/components/content-dev-hero-section/content-dev-hero-section.component.ts
> +
To keep the component lean and ensure readability and maintainability, the 'heroTexts' variable can be moved to its own Typescript file in the data module.

2023-09-07 07:12 UTC, levy-web commented
@AnnaL001 fixed the issues kindly review

2023-09-07 07:37 UTC, AnnaL001 commented on libs/features/pages/content-development/src/lib/main/content-development-page/content-development-page.component.scss
> +
For cosmetic purposes, the whitespace can be removed

2023-09-07 07:41 UTC, AnnaL001 requested changes
Good job so far, just a couple of changes before this is merged

2023-09-07 07:58 UTC, AnnaL001 commented on libs/features/pages/content-development/src/lib/components/content-dev-hero-section/content-dev-hero-section.component.ts
> +  }
Nicely done, just one more change. You can also move the buttonData to the same file as that of the 'heroTexts' variable and reference it the same way as that of the 'heroTexts' variable.

2023-09-07 08:32 UTC, levy-web commented
@AnnaL001 done with the changes

2023-09-07 09:16 UTC, AnnaL001 submitted a review, later dismissed

2023-09-08 09:15 UTC, LemmyMwaura approved these changes

2023-09-08 09:15 UTC, merged