Create the booklets page hero section #15
italanta/elewa-website pull request #177
Opened 2023-09-04 06:48 UTC by levy-web

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Reference the issue related to this PR as shown below. Every issue has it's own number you can find the issue numbers [here](https://github.com/italanta/italanta-apps/issues).

Fixes # (issue) - *Example*: Fixes #10, #20 NOTE: GitHub issue numbers should be prefixed with **#** to aid with issue tracking.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Screenshot (optional)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**: (optional)

- Firmware version:
- Hardware:
- Toolchain:
- SDK:

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-09-07 08:18 UTC, AnnaL001 commented on libs/features/pages/booklets-page/src/lib/components/booklets-hero-section/booklets-hero-section.component.ts
> +
For the purposes of readability and maintainability and keeping the component clean, the 'herotexts' and 'buttonData' variable content can be moved to a Typescript file within the data module and referenced from there.

2023-09-07 08:19 UTC, AnnaL001 requested changes
Good job, a number of changes before this is merged

2023-09-07 08:57 UTC, levy-web commented
@AnnaL001 completed the fix kindly review

2023-09-08 09:20 UTC, LemmyMwaura commented
Work on only 2 and 3 pointers now

2023-09-08 09:20 UTC, closed without merging