🎨 Create contact page form
italanta/elewa-website pull request #188
Opened 2023-09-04 16:21 UTC by darlene9497

# Description

This pull request introduces a user-friendly contact form section on the Contact page, enhancing communication between users and the platform. The feature is implemented as per the provided design specifications, ensuring pixel-perfect rendering and responsiveness across various devices.

Fixes #184 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Screenshot
![Screenshot from 2023-09-08 14-44-28](https://github.com/italanta/elewa-website/assets/117742892/dc55055d-68ae-4df9-a936-7a885b46f06a)

Tablet view
![Screenshot from 2023-09-08 14-43-55](https://github.com/italanta/elewa-website/assets/117742892/7b389c30-78f1-43c7-9142-f5123084ffc3)

Phone view
![Screenshot from 2023-09-08 14-42-16](https://github.com/italanta/elewa-website/assets/117742892/16d4f5e4-c70c-48cc-8324-ed40874ace59)

## How Has This Been Tested?

- [x] Test A - The server runs successfully without generating any new warnings

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2023-09-07 08:48 UTC, AnnaL001 commented on libs/features/pages/contact-page/src/lib/components/contact-page-form-section/contact-page-form-section.component.scss
> +
To ensure the 'contact text' section of the contact form remains at the top, the align items property should be set to flex-start

2023-09-07 08:52 UTC, AnnaL001 commented on libs/features/pages/contact-page/src/lib/features-pages-contact-page.module.ts
Kindly, ensure the order of imports; the elements imports should appear before local imports

2023-09-07 08:57 UTC, AnnaL001 commented on libs/features/pages/contact-page/src/lib/components/contact-page-form-section/contact-page-form-section.component.ts
> +    });
For the sake of separation of concerns, this can be moved to its own method which is then called within an ngOnInit() method.

2023-09-07 09:01 UTC, AnnaL001 commented on libs/features/pages/contact-page/src/lib/components/contact-page-form-section/contact-page-form-section.component.ts
> +  }
For purposes of keeping the component lean and ensuring readability and maintainability, the 'sendButtonData' variable content should be moved to a Typescript file in the data module

2023-09-07 09:13 UTC, AnnaL001 requested changes
Good job so far, just a couple of changes.

For uniformity, the 'select option' form field can be aligned like the rest of the form fields.

2023-09-07 12:06 UTC, darlene9497 commented
@AnnaL001 please review the changes I have made. Make reference to the screenshot as well in regards to the select option field

2023-09-08 09:38 UTC, LemmyMwaura commented
https://github.com/italanta/elewa-website/assets/20738858/92da1eb0-a1c2-457b-9935-8e49f8c13c73


Design should be cleaner. A few things overflow or are wrongly placed at certain window sizes.

2023-09-08 11:47 UTC, darlene9497 commented
@LemmyMwaura I have made the necessary changes and re-uploaded the screenshots. I had placed the social-icons wrongly

2023-09-11 05:53 UTC, LemmyMwaura commented
Very Good job on this but I've gone with #184 smoother responsive design.

2023-09-11 05:53 UTC, closed without merging