Create the consultancy hero section #176
italanta/elewa-website pull request #193
Opened 2023-09-05 08:35 UTC by Yhworld

# Description

A Hero section on the consultancy page that captures attention and introduces the page content.

Fixes #176 

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

## Screenshot (optional)
![Screenshot from 2023-09-05 10-12-11](https://github.com/italanta/elewa-website/assets/74947307/9602fe47-a0e7-4ecd-a3ab-c7fba9dfcbfa)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**: (optional)

- Firmware version:
- Hardware:
- Toolchain:
- SDK:

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-09-05 08:37 UTC, Yhworld commented
@LemmyMwaura

2023-09-07 11:43 UTC, AnnaL001 commented on libs/features/pages/consultancy-page/src/lib/components/consultancy-hero-section/consultancy-hero-section.component.scss
> +    // margin-left: 20rem;
To eliminate dead code, commented out code should be removed.

2023-09-07 11:45 UTC, AnnaL001 commented on libs/features/pages/consultancy-page/src/lib/components/consultancy-hero-section/consultancy-hero-section.component.ts
> +  }
To keep the component lean and ensure readability and maintainability, the 'heroTexts' and 'buttonData' variable content can be moved to a Typescript file in the data module.

2023-09-07 11:54 UTC, AnnaL001 requested changes
Nicely done, just a few adjustments.

Also, the left margin of the hero section and the top bar can be reduced, to match the specified design.

2023-09-07 15:08 UTC, Yhworld commented
@AnnaL001  done kindly review

2023-09-08 12:05 UTC, LemmyMwaura approved these changes

2023-09-08 12:06 UTC, LemmyMwaura approved these changes

2023-09-08 12:06 UTC, merged