Consultancy hero section #176
italanta/elewa-website pull request #195
Opened 2023-09-05 10:10 UTC by PerisOduol618

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Reference the issue related to this PR as shown below. Every issue has it's own number you can find the issue numbers [here](https://github.com/italanta/italanta-apps/issues).

Fixes # (issue) - *Example*: Fixes #10, #20 NOTE: GitHub issue numbers should be prefixed with **#** to aid with issue tracking.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Screenshot (optional)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**: (optional)

- Firmware version:
- Hardware:
- Toolchain:
- SDK:

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-09-07 11:56 UTC, AnnaL001 commented on libs/features/pages/consultancy-page/src/lib/components/consultancy-hero-section/consultancy-hero-section.component.html
> +  <!-- </div> -->
To eliminate dead code, commented out code should be removed

2023-09-07 11:58 UTC, AnnaL001 commented on libs/features/pages/consultancy-page/src/lib/components/consultancy-hero-section/consultancy-hero-section.component.ts
> +  };
To keep the component lean and ensure readability and maintainability, the 'heroSectionData' and 'buttonData' variable content can be moved to a Typescript file in the data module and referenced from there

2023-09-07 11:59 UTC, AnnaL001 commented on libs/features/pages/consultancy-page/src/lib/consultancy-page.module.ts
Kindly, observe the order of imports; the elements imports should appear before local imports.

2023-09-07 12:04 UTC, AnnaL001 requested changes
Good job, a few changes before this is merged.

Also for the hero section to match the specified design, the left margin can be reduced so that it matches that of the top navigation bar

2023-09-11 05:55 UTC, LemmyMwaura commented
Closing this as it's been resolved

2023-09-11 05:55 UTC, closed without merging