Create reusable pricing list component #141
italanta/elewa-website pull request #197
Opened 2023-09-05 11:37 UTC by Mutagah

# Description

Created the `elewa-price-list component`, added dummy data and made the user interface responsive.

## Type of change

Please delete options that are not relevant.

[ ] New feature (non-breaking change which adds functionality)
[ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Screenshot (optional)
![Screenshot from 2023-09-01 15-15-36](https://github.com/italanta/elewa-website/assets/106149210/bc4bd722-a4c0-423e-b678-94a4c525e4d9)
![Screenshot from 2023-09-04 10-27-36](https://github.com/italanta/elewa-website/assets/106149210/e5bfefa2-674e-47d1-b7df-3a89ca2148f9)
![Screenshot from 2023-09-04 10-27-52](https://github.com/italanta/elewa-website/assets/106149210/0f238702-9760-4e77-ad0e-111deb0316cc)

## How Has This Been Tested?

Through actual rendering of the required component on the web browser and checking it side by side with the design.

## Checklist

 [ ] My code follows the style guidelines of this project
 [ ] I have performed a self-review of my code
 [ ] Any dependent changes have been merged

2023-09-07 06:21 UTC, LemmyMwaura requested changes
Your component is clean but your resolution to the merge conflict removes a lot of code from the codebase. Resolve again kindly

2023-09-07 12:09 UTC, AnnaL001 commented on libs/elements/cards/src/lib/components/elewa-price-item-card/elewa-website-price-item-card.component.scss
> -    // width: 40vw;
To eliminate dead code, commented out code should be removed.

2023-09-07 12:12 UTC, AnnaL001 requested changes
Good job, just a couple of changes

2023-09-08 11:55 UTC, LemmyMwaura approved these changes

2023-09-08 11:56 UTC, LemmyMwaura approved these changes

2023-09-08 11:57 UTC, AnnaL001 approved these changes

2023-09-08 11:57 UTC, merged