💄 #176 create the consultancy hero section
italanta/elewa-website pull request #207
Opened 2023-09-06 12:51 UTC by jbdura

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Reference the issue related to this PR as shown below. Every issue has it's own number you can find the issue numbers [here](https://github.com/italanta/italanta-apps/issues).

Fixes #176 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Screenshot (optional)
![Screenshot from 2023-09-06 15-37-01](https://github.com/italanta/elewa-website/assets/99818207/0dbdf213-b6fe-446c-a8e6-6a1d3352d29f)
![Screenshot from 2023-09-06 15-36-30](https://github.com/italanta/elewa-website/assets/99818207/3ef0ba38-81e1-4c87-bad9-5cd7236f8124)

![Screenshot from 2023-09-06 15-36-15](https://github.com/italanta/elewa-website/assets/99818207/01bf593a-c20d-4516-8f83-6be09f57e150)
## How Has This Been Tested?

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2023-09-08 07:20 UTC, AnnaL001 commented on libs/features/pages/consultancy-page/src/lib/components/consultancy-hero-section/consultancy-hero-section.component.scss
> +  background: #DBC2F5 0% 0% no-repeat padding-box;
For reuse of colors, use CSS variables specified in elements/theming/_variables.scss for specifying colors/background colors.

2023-09-08 07:21 UTC, AnnaL001 commented on libs/features/pages/consultancy-page/src/lib/components/consultancy-hero-section/consultancy-hero-section.component.scss
> +      background: transparent linear-gradient(90deg, #DBC2F500 0%, #DBC2F5E6 100%) 0% 0% no-repeat padding-box;
Same here, for linear gradient

2023-09-08 07:21 UTC, AnnaL001 commented on libs/features/pages/consultancy-page/src/lib/components/consultancy-hero-section/consultancy-hero-section.component.scss
> +      background: transparent linear-gradient(90deg, #DBC2F500 0%, #DBC2F5E6 100%) 0% 0% no-repeat padding-box;
Same here

2023-09-08 07:23 UTC, AnnaL001 commented on libs/features/pages/consultancy-page/src/lib/components/consultancy-hero-section/consultancy-hero-section.component.ts
> +
To keep the component lean and ensure readability and maintainability, the 'herotexts' and 'buttonData' variable content can be moved to a Typescript file in the data module

2023-09-08 07:24 UTC, AnnaL001 requested changes
Nicely done, just a couple of changes

2023-09-08 08:23 UTC, jbdura commented
All recommended fixes completed

2023-09-11 07:17 UTC, closed without merging

2023-09-11 07:17 UTC, LemmyMwaura commented
Closing this as it's already been implemented