About page hero section #183
italanta/elewa-website pull request #210
Opened 2023-09-07 07:24 UTC by PerisOduol618

# Description

A hero section on the about page that introduces the page content

Reference the issue related to this PR as shown below. Every issue has it's own number you can find the issue numbers [here](https://github.com/italanta/elewa-website/issues/183).

Fixes # (issue) - *Example*: Fixes #183 NOTE: GitHub issue numbers should be prefixed with **#** to aid with issue tracking.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Screenshot (optional)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**: (optional)

- Firmware version:
- Hardware:
- Toolchain:
- SDK:

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-09-08 07:32 UTC, AnnaL001 commented on libs/features/pages/about/src/lib/components/about-hero-section/about-hero-section.component.scss
> +    color: #000000;
For reuse of colors, use CSS variables specified in elements/theming/_variables.scss for colors/background colors

2023-09-08 07:36 UTC, AnnaL001 commented on libs/features/pages/about/src/lib/components/about-hero-section/about-hero-section.component.ts
> +
Just like the 'image' variable, the 'heroAboutData' variable content can be moved to the same Typescript file as the 'heroAboutData' and referenced from there.

2023-09-08 07:37 UTC, AnnaL001 commented on libs/features/pages/about/src/lib/features-pages-about.module.ts
> +import { TextsModule } from '@elewa-website/elements/layout/texts';
Kindly, observe the order of imports; elements imports should appear before local imports

2023-09-08 07:38 UTC, AnnaL001 requested changes
Good work, just a few changes

2023-09-08 12:06 UTC, PerisOduol618 commented
@AnnaL001 Done

2023-09-13 08:35 UTC, LemmyMwaura approved these changes

2023-09-13 08:35 UTC, merged