🎨 create the home landing page #5
italanta/elewa-website pull request #213
Opened 2023-09-07 09:12 UTC by jbdura

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Reference the issue related to this PR as shown below. Every issue has it's own number you can find the issue numbers [here](https://github.com/italanta/italanta-apps/issues).

Fixes #5

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Screenshot (optional)
![Screenshot from 2023-09-07 12-04-11](https://github.com/italanta/elewa-website/assets/99818207/0b880ab4-7739-4ac5-ac5d-39fa10ee9522)
![Screenshot from 2023-09-07 11-53-02](https://github.com/italanta/elewa-website/assets/99818207/af495543-6306-4858-9a40-9bbc3dfbefe4)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2023-09-08 07:47 UTC, AnnaL001 commented on libs/features/pages/home/src/lib/components/home-hero-section/home-hero-section.component.scss
> +  background: #F9F8F4 0% 0% no-repeat padding-box;
For reuse of colors, use CSS variables specified in elements/theming/_variables.scss for specifying colors/background colors

2023-09-08 07:47 UTC, AnnaL001 commented on libs/features/pages/home/src/lib/components/home-hero-section/home-hero-section.component.scss
> +      color: #000000;
Same here

2023-09-08 08:30 UTC, jbdura commented
Requested edits in styles complete

2023-09-08 09:33 UTC, AnnaL001 commented on libs/features/pages/home/src/lib/components/home-hero-section/home-hero-section.component.scss
> +      // align-items: flex-start;
To eliminate dead code, commented out/unused code should be removed

2023-09-08 09:34 UTC, AnnaL001 commented on libs/features/pages/home/src/lib/components/home-hero-section/home-hero-section.component.ts
> +  };
To keep the component lean and ensure readability and maintainability, the 'buttonData', 'herotexts' and 'imageConfig' variable content can be moved to a Typescript file in the data module

2023-09-08 09:36 UTC, AnnaL001 requested changes
Nicely done, just a few adjustments

2023-09-08 10:59 UTC, jbdura commented
Requested changes done

2023-09-14 07:01 UTC, LemmyMwaura requested changes

2023-09-14 07:01 UTC, LemmyMwaura commented on libs/features/pages/home/src/lib/main/home/home-page.component.html
> +</div>
This was wrapped by the main page component. you should leave that way. Just add your component where it should be.

2023-09-14 07:01 UTC, LemmyMwaura commented on libs/models/schema/ui/images/src/lib/image-config.ts
> +  }
This was deleted. don't add it back

2023-09-14 14:59 UTC, jbdura commented
Updated branch with current changes

2023-09-18 07:01 UTC, LemmyMwaura commented
Closing this as it's been resolved

2023-09-18 07:01 UTC, closed without merging