Create menu solutions component on the header #186
italanta/elewa-website pull request #214
Opened 2023-09-07 18:50 UTC by levy-web

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Reference the issue related to this PR as shown below. Every issue has it's own number you can find the issue numbers [here](https://github.com/italanta/italanta-apps/issues).

Fixes # (issue) - *Example*: Fixes #10, #20 NOTE: GitHub issue numbers should be prefixed with **#** to aid with issue tracking.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Screenshot (optional)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**: (optional)

- Firmware version:
- Hardware:
- Toolchain:
- SDK:

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-09-08 09:39 UTC, AnnaL001 commented on libs/elements/layout/header/src/lib/components/header-menu/header-menu.component.scss
> +    background-color: white;
For reuse of colors, use CSS variables specified in elements/theming/_variables.scss  for specifying colors and background colors

2023-09-08 09:39 UTC, AnnaL001 commented on libs/elements/layout/header/src/lib/components/header-menu/header-menu.component.scss
> +    background-color: #eaeaea;
Same here

2023-09-08 09:40 UTC, AnnaL001 commented on libs/elements/layout/header/src/lib/components/menu-item/menu-item.component.scss
> +    background: transparent linear-gradient(307deg, #F2AD69 0%, #F2AD6900 100%) 0% 0% no-repeat padding-box;
Same here for the linear gradient

2023-09-08 09:40 UTC, AnnaL001 commented on libs/elements/layout/header/src/lib/components/menu-item/menu-item.component.scss
> +        background: transparent linear-gradient(180deg, #E69083 0%, #E6908300 100%) 0% 0% no-repeat padding-box;
Same here

2023-09-08 09:41 UTC, AnnaL001 commented on libs/elements/layout/header/src/lib/components/menu-item/menu-item.component.scss
> +        background: transparent linear-gradient(180deg, #E69083 0%, #E6908300 100%) 0% 0% no-repeat padding-box;
Same here

2023-09-08 09:41 UTC, AnnaL001 commented on libs/elements/layout/header/src/lib/components/menu-item/menu-item.component.scss
> +        background: transparent linear-gradient(180deg, #F2CF73 0%, #F2CF7300 100%) 0% 0% no-repeat padding-box;
Same here

2023-09-08 09:41 UTC, AnnaL001 commented on libs/elements/layout/header/src/lib/components/menu-item/menu-item.component.scss
> +        background: transparent linear-gradient(180deg, #F2CF73 0%, #F2CF7300 100%) 0% 0% no-repeat padding-box;
Same here

2023-09-08 09:41 UTC, AnnaL001 commented on libs/elements/layout/header/src/lib/components/menu-item/menu-item.component.scss
> +        background: transparent linear-gradient(180deg, #F2CF73 0%, #F2CF7300 100%) 0% 0% no-repeat padding-box;
Same here

2023-09-08 09:41 UTC, AnnaL001 commented on libs/elements/layout/header/src/lib/components/menu-item/menu-item.component.scss
> +        background: transparent linear-gradient(90deg, #DBC2F500 0%, #DBC2F5E6 100%) 0% 0% no-repeat padding-box;
Same here

2023-09-08 09:41 UTC, AnnaL001 commented on libs/elements/layout/header/src/lib/components/menu-item/menu-item.component.scss
> +        background: transparent linear-gradient(90deg, #DBC2F500 0%, #DBC2F5E6 100%) 0% 0% no-repeat padding-box;
Same here

2023-09-08 09:44 UTC, AnnaL001 requested changes
Nicely done, just a few changes

2023-09-08 10:24 UTC, levy-web commented
@AnnaL001 done with the fixes

2023-09-16 15:59 UTC, LemmyMwaura approved these changes

2023-09-16 16:07 UTC, merged