Consultancy page issue#208
italanta/elewa-website pull request #215
Opened 2023-09-08 07:42 UTC by Dancunrandy

# Description
Reused the component created in #28 to create learning services component that displays the learning devices section on the consultancy page.

Fixes # (issue) - *Example*: Fixes #10, #20 NOTE: GitHub issue numbers should be prefixed with **#** to aid with issue tracking.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Screenshot 
![Screenshot from 2023-09-08 10-35-19](https://github.com/italanta/elewa-website/assets/73400072/0e5ba2ab-8bda-4d08-98e5-bdfc06e7a6f0)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**: (optional)

- Firmware version:
- Hardware:
- Toolchain:
- SDK:

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-09-08 09:50 UTC, AnnaL001 commented on libs/features/pages/consultancy-page/src/lib/Component/elewa-website-learning-services/elewa-website-learning-services.component.scss
> +  font: normal normal medium 62px/80px DM Sans;
For reuse of fonts, use CSS variables specified in elements/theming/_variables.scss for specifying font family

2023-09-08 11:36 UTC, AnnaL001 commented on libs/features/pages/consultancy-page/src/lib/Component/elewa-website-learning-services/elewa-website-learning-services.component.ts
> +  @Input() cardsData!: InfoCard[];
As this is not reusable, the 'cardsData' variable should be a normal variable instead of an input variable

2023-09-08 11:37 UTC, AnnaL001 requested changes
Good job, just a few adjustments

2023-09-08 11:59 UTC, Dancunrandy commented
@AnnaL001 , Fixed the issue

2023-09-11 09:17 UTC, LemmyMwaura submitted a review, later dismissed

2023-09-11 09:31 UTC, merged