Issue#1/ft website header
italanta/elewa-website pull request #33
Opened 2023-08-09 04:42 UTC by jbdura

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Reference the issue related to this PR as shown below. Every issue has it's own number you can find the issue numbers [here](https://github.com/italanta/italanta-apps/issues).

Fixes # (issue) - *Example*: Fixes #10, #20 NOTE: GitHub issue numbers should be prefixed with **#** to aid with issue tracking.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Screenshot (optional)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**: (optional)

- Firmware version:
- Hardware:
- Toolchain:
- SDK:

## Checklist

- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ x] Any dependent changes have been merged and published in downstream modules

![Screenshot from 2023-08-07 22-48-42](https://github.com/italanta/elewa-website/assets/99818207/41b86f8f-f36c-4bb3-a58d-74046b7e9898)

2023-08-09 13:37 UTC, LemmyMwaura commented
Update your PR description. I'll review after that is done

2023-08-09 16:28 UTC, jbdura commented
Edited the pr description

2023-08-11 13:44 UTC, jrosseel requested changes

2023-08-11 13:44 UTC, jrosseel commented on libs/elements/layout/header/src/lib/header/header.component.scss
> +        background-color: #333;
Colours always at root level

2023-08-11 13:44 UTC, jrosseel commented on libs/elements/layout/header/src/lib/header/header.component.scss
> +            background-color: #f5f5f5;
Direct colour

2023-08-11 13:44 UTC, jrosseel commented on libs/elements/layout/header/src/lib/header/header.component.scss
> +        background-color: white;
Direct colour

2023-08-11 13:44 UTC, jrosseel commented on libs/elements/layout/header/src/lib/header/header.component.scss
> +      background-color: #010e3a;
Direct colour

2023-08-11 13:44 UTC, jrosseel commented on libs/elements/layout/header/src/lib/header/header.component.ts
> +  /**
This JsDoc should be on top of the class, else it won';t work

2023-08-11 13:44 UTC, jrosseel commented on libs/elements/layout/header/src/lib/header/header.component.ts
> +  // To check if navigation menu is open or not
JsDoc

2023-08-11 13:44 UTC, jrosseel commented on libs/elements/layout/header/src/lib/header/header.component.ts
> +  constructor () {
Don't put constructor if empty.

Constructor should be on top of normal methods

2023-08-11 13:44 UTC, jrosseel commented on libs/elements/layout/header/src/lib/header/header.component.ts
> +  logoUrl = "https://res.cloudinary.com/dyl3rncv3/image/upload/v1675690297/elewa-group-website/Icons/SVG/_Logo/Logo_White_arvoyx.svg"
Perhaps for now, define as a constant at file level

2023-08-11 13:44 UTC, jrosseel commented on libs/elements/layout/header/src/lib/header/header.component.ts
> +
const LOGO_URL = .....

2023-08-11 13:44 UTC, jrosseel commented on libs/elements/layout/header/src/lib/header/header.component.ts
> +  logoUrl = "https://res.cloudinary.com/dyl3rncv3/image/upload/v1675690297/elewa-group-website/Icons/SVG/_Logo/Logo_White_arvoyx.svg"
logoUrl = LOGO_URL

2023-08-12 18:54 UTC, jbdura commented
Made the required changes.

2023-08-21 06:01 UTC, LemmyMwaura commented
We are closing this as it's been resolved in #26. Suppose you need feedback reply below.

2023-08-21 06:01 UTC, closed without merging