Website header #1
italanta/elewa-website pull request #37
Opened 2023-08-09 18:42 UTC by darlene9497

# Description

This pull request aims to implement a website header for improved navigation on the Elewa website. The header is designed to provide a user experience and has the Elewa logo, transparent background, legible black font, and contact button features.

Fixes https://github.com/italanta/elewa-website/issues/1

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Screenshot (optional)
![Screenshot from 2023-08-09 21-00-46](https://github.com/italanta/elewa-website/assets/117742892/7a3a255c-b395-4c94-af61-a199851a70ff)

## How Has This Been Tested?

- [x] Test A - Relied on visual evaluations, as depicted in the screenshot above, and successful compilation on the live server as depicted in the screenshot below.
![Screenshot from 2023-08-09 21-03-32](https://github.com/italanta/elewa-website/assets/117742892/226bb2d1-6d2a-4390-afc6-5374f377dfb4)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

2023-08-10 11:37 UTC, LemmyMwaura requested changes

2023-08-10 11:37 UTC, LemmyMwaura commented on apps/elewa-website/src/i18n.config.ts
> +});
No need for this as I had already set up the translations, just sync the latest changes

2023-08-10 11:37 UTC, LemmyMwaura commented on apps/elewa-website/src/main.ts
> +
also this, no need.

2023-08-10 11:37 UTC, LemmyMwaura commented on apps/elewa-website/tsconfig.app.json
> +    ]
also here

2023-08-10 11:37 UTC, LemmyMwaura commented on apps/elewa-website/tsconfig.server.json
> +      "@angular/localize"
also here

2023-08-10 11:37 UTC, LemmyMwaura commented on libs/elements/layout/header/src/lib/components/header/header.component.scss
> +    align-items: center;
Good job composing your styles,

2023-08-10 11:37 UTC, LemmyMwaura commented on package.json
> +    "@fortawesome/fontawesome-free": "^6.4.2",
For font awesome, add a CDN link to the root index.html file

2023-08-10 11:37 UTC, LemmyMwaura commented on libs/elements/layout/header/src/lib/components/header/header.component.html
> +        </ul>
Write a custom directive to add toggle logic reactivity

2023-08-10 11:38 UTC, LemmyMwaura commented
Good job on your PR desc and commits.

2023-08-11 11:50 UTC, darlene9497 commented
I have made the necessary changes and looking forward to the feedback

2023-08-15 13:12 UTC, LemmyMwaura requested changes
Just One final thing. Also, use the directive to toggle the menu from active to inactive. This is not a must you can also do this in the header itself. If you choose option two just delete the directive

2023-08-15 13:12 UTC, LemmyMwaura commented on apps/elewa-website/src/app/toggle-menu.directive.ts
> +}
The directive should be in the header and not the app module.

2023-08-16 05:19 UTC, closed without merging