Reusable button#23
italanta/elewa-website pull request #41
Opened 2023-08-10 07:54 UTC by Alexotieno1717

# Description

Created a reusable normal button component that I can reuse anywhere it's needed across the application

Reference the issue related to this PR as shown below. Every issue has its own number you can find the issue number [here](https://github.com/italanta/elewa-website/issues/23).

## Type of change

- [✅] New feature (non-breaking change which adds functionality)

## Screenshot (optional)
The Website before the changes.

![Screenshot from 2023-08-10 10-27-31](https://github.com/italanta/elewa-website/assets/43090738/e3158143-deee-4147-9a48-e2e884a48a88)

The Website after implementing the Reusable Normal button component.

![Screenshot from 2023-08-10 09-45-32](https://github.com/italanta/elewa-website/assets/43090738/1865f2ae-b159-4596-8277-47c689bc4268)

## Checklist

- [✅] My code follows the style guidelines of this project
- [✅] I have performed a self-review of my code
- [✅] I have commented my code, particularly in hard-to-understand areas
- [✅] I have made corresponding changes to the documentation

2023-08-10 12:26 UTC, LemmyMwaura requested changes
Good first attempt. Just a few changes remaining

2023-08-10 12:26 UTC, LemmyMwaura commented on apps/elewa-website/src/app/app.component.ts
> +  };
No need to push this, as our app component does not need it.

2023-08-10 12:26 UTC, LemmyMwaura commented on libs/elements/layout/buttons/src/lib/normal-button/normal-button.component.ts
> +  }
Good

2023-08-10 12:26 UTC, LemmyMwaura commented on libs/elements/layout/buttons/src/lib/normal-button/normal-button.component.ts
> +import { ButtonData } from "../../../../../../models/schema/ui/buttons/button.interface";
Should use aliased imports. `@elewa...`

2023-08-10 12:53 UTC, Alexotieno1717 commented
@LemmyMwaura I have made changes to this PR.

2023-08-10 12:54 UTC, Alexotieno1717 commented on libs/elements/layout/buttons/src/lib/normal-button/normal-button.component.ts
> +import { ButtonData } from "../../../../../../models/schema/ui/buttons/button.interface";
okay noted

2023-08-15 13:24 UTC, LemmyMwaura commented on libs/elements/layout/buttons/src/lib/normal-button/normal-button.component.ts
> +  @Input() buttonData:ButtonData = {};
Replace with `@Input() buttonData !: ButtonData`

2023-08-23 09:19 UTC, LemmyMwaura requested changes
Just One last thing, kindly resolve this

2023-08-23 09:19 UTC, LemmyMwaura commented on libs/elements/layout/buttons/src/lib/normal-button/normal-button.component.html
> +  <ng-content></ng-content>
Interpolate this text {{ yourProperty }}

2023-08-23 09:21 UTC, LemmyMwaura commented on libs/elements/layout/buttons/src/lib/normal-button/normal-button.component.ts
> +  selector: 'elewa-normal-button',
Remove this and then rename to `elewa-website-normal-button`.

2023-08-25 12:00 UTC, closed without merging