Image container
italanta/elewa-website pull request #42
Opened 2023-08-10 08:37 UTC by T-erry

# Description

Created an image container component <elewa-website-elewa-image-container [imageconfigs]="imageconfigs">, this component can be reused anywhere in the site.

Fixes #19 Create an image-container component 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Screenshot (optional)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

###This was tested through viewing on the browser by using the nx serve command after Compile was successful

- [x] Test A
- [x] Test B

**Test Configuration**: (optional)

- Firmware version:
- Hardware:
- Toolchain:
- SDK:

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2023-08-10 12:34 UTC, LemmyMwaura requested changes
Good job on your first attempt. Still a few changes remaining

2023-08-10 12:34 UTC, LemmyMwaura commented on libs/elements/layout/images/src/lib/elewa-image-container/elewa-image-container.component.html
> +</div>
Good job here but this should accept just one imageConfig.

2023-08-10 12:34 UTC, LemmyMwaura commented on libs/elements/layout/images/src/lib/elewa-image-container/elewa-image-container.component.ts
> +}
Good job

2023-08-10 12:34 UTC, LemmyMwaura commented on libs/models/schema/ui/images/src/index.ts
> +export { ImageConfig, ImageVisualisation }
Good but it should be exported this way `export * from './lib/{file-path}'`

2023-08-10 16:36 UTC, Lawrence137 commented
working on this with @Whitneyjoymuchira and @BrianWahungu

2023-08-15 13:26 UTC, LemmyMwaura commented on libs/features/pages/home/src/lib/main/home/home-page.component.ts
> +}
No need to push these changes as our HomePage component does not need this import. Any Component that needs this will import it.

2023-08-21 06:28 UTC, LemmyMwaura commented
Kindly resolve the above.

2023-08-31 12:15 UTC, LemmyMwaura approved these changes

2023-09-01 07:02 UTC, LemmyMwaura approved these changes

2023-09-01 07:07 UTC, merged