Website header #1
italanta/elewa-website pull request #47
Opened 2023-08-10 11:41 UTC by KaranjaK

# Description

The changes effected are:
1. Creation o a header.
2. Addition of the Menu List and close icons in to power responsiveness of the header once loaded on Tablet and phone screens. 
3. Added ngx translate dependency to power translation 

Reference the issue related to this PR as shown below. Every issue has it's own number you can find the issue numbers [here](https://github.com/italanta/italanta-apps/issues).

Fixes #1  - 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Screenshot (optional)
![image](https://github.com/italanta/elewa-website/assets/52041084/84b7cff8-b6fd-4469-9761-b2e322fbd280)
![image](https://github.com/italanta/elewa-website/assets/52041084/2d4bcd46-5a94-4bd3-a2c8-f12912d0221f)

**Test Configuration**: (optional)

- Firmware version:
- Hardware:
- Toolchain:
- SDK:

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-08-10 12:58 UTC, LemmyMwaura requested changes

2023-08-10 12:58 UTC, LemmyMwaura commented on libs/elements/layout/header/src/lib/header.routing.ts
> +})
Header does not need to have routing set

2023-08-10 12:58 UTC, LemmyMwaura commented on libs/features/pages/home/src/lib/home.routing.ts
>  ];
Should still be here. The home page needs the route to be set

2023-08-10 12:58 UTC, LemmyMwaura commented on package.json
> +    "bootstrap-icons": "^1.10.5",
We use font-awesome icons. I'll add a CDN for this that you can get by syncing the latest changes

2023-08-15 13:36 UTC, LemmyMwaura commented
Kindly resolve the issues above so that we merge this

2023-08-15 14:30 UTC, KaranjaK commented
Well noted. Kindly allow me to do it tomorrow morning before 6am

On Tue, Aug 15, 2023 at 4:36 PM Lemmy ***@***.***> wrote:

> Kindly resolve the issues above so that we merge this
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/italanta/elewa-website/pull/47#issuecomment-1678946480>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMNBK7FSXWXAIJFK4TA46S3XVN3NNANCNFSM6AAAAAA3LLZWYY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-08-21 06:03 UTC, LemmyMwaura commented
We are closing this as it's been resolved in #26. Suppose you need feedback reply below.

2023-08-21 06:03 UTC, closed without merging