✨ Issue#27 create reusable content text component
italanta/elewa-website pull request #53
Opened 2023-08-11 11:10 UTC by jbdura

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Reference the issue related to this PR as shown below. Every issue has it's own number you can find the issue numbers [here](https://github.com/italanta/italanta-apps/issues).

Fixes # (issue) - Added reusable 

## Type of change
Added reusable component

Please delete options that are not relevant.

## Screenshot (optional)

![Screenshot from 2023-08-11 13-47-10](https://github.com/italanta/elewa-website/assets/99818207/e3765785-6ad4-48b0-8502-6a19a275f631)

## Checklist

- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [x ] My changes generate no new warnings

2023-08-12 18:49 UTC, jbdura commented
Hello, done the required changes

2023-08-15 12:05 UTC, LemmyMwaura requested changes
You've mixed two issues into one. Kindly sort that.

2023-08-15 12:10 UTC, LemmyMwaura requested changes
You've mixed two different issues. Kindly fix that.

2023-08-15 12:10 UTC, LemmyMwaura commented on libs/elements/layout/header/src/lib/header/header.component.ts
> +
No need for this. Also, JSDoc comments go above the item your describing.

2023-08-15 12:10 UTC, LemmyMwaura commented on libs/elements/layout/header/src/lib/header/header.component.ts
> +  }
remove the empty constructor

2023-08-15 12:48 UTC, closed without merging