Reusable infocard component#28
italanta/elewa-website pull request #59
Opened 2023-08-14 20:19 UTC by Marionwanyama23

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Reference the issue related to this PR as shown below. Every issue has it's own number you can find the issue numbers [here](https://github.com/italanta/italanta-apps/issues).

Fixes # (issue) - *Example*: Fixes #10, #20 NOTE: GitHub issue numbers should be prefixed with **#** to aid with issue tracking.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Screenshot (optional)
![image screenshot](https://raw.githubusercontent.com/Marionwanyama23/elewa-website/reusable-Infocard-component%2328/libs/elements/cards/src/lib/elewa-info-card/info-card.png)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**: (optional)

- Firmware version:
- Hardware:
- Toolchain:
- SDK:

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2023-08-15 12:49 UTC, LemmyMwaura requested changes
Good job. Just clean up a few changes. Also update your PR description and remove the info card image from the codebase. Just Google how to add it to GitHub markdown.

2023-08-15 12:49 UTC, LemmyMwaura commented on libs/features/pages/home/src/lib/main/home/home-page.component.html
> +  <elewa-website-elewa-info-card [cardInfo]="{title: 'Course design', description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Praesentium minima tempora magnam iusto.', icon: 'https:/
Custom Mock data should be stored in a data module. If not specified in the issue, then there's no need to push this changes

2023-08-15 12:49 UTC, LemmyMwaura commented on libs/elements/cards/src/lib/elewa-info-card/elewa-info-card.component.ts
> +}
replace with `@Input() cardInfo!: InfoCard`

2023-08-21 06:45 UTC, LemmyMwaura commented
Kindly make the changes requested.

2023-08-21 10:04 UTC, Marionwanyama23 commented
I've made the necessary changes please review my code

On Mon, Aug 21, 2023, 09:46 Lemmy ***@***.***> wrote:

> Kindly make the changes requested.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/italanta/elewa-website/pull/59#issuecomment-1685745250>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZPVABA6EAWIJSN24PV27RLXWL72ZANCNFSM6AAAAAA3QFWPVU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-08-25 12:04 UTC, LemmyMwaura commented
Closing as this has been completed in #48

2023-08-25 12:04 UTC, closed without merging