🎨 #14 create reusable project item component
italanta/elewa-website pull request #76
Opened 2023-08-21 08:54 UTC by jbdura

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Reference the issue related to this PR as shown below. Every issue has it's own number you can find the issue numbers [here](https://github.com/italanta/italanta-apps/issues).

Fixes # (issue) - *Example*: Fixes #10, #20 NOTE: GitHub issue numbers should be prefixed with **#** to aid with issue tracking.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Screenshot (optional)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**: (optional)

- Firmware version:
- Hardware:
- Toolchain:
- SDK:

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-08-21 11:37 UTC, LemmyMwaura requested changes
Good job so far. Update the Pr description and also clean up the design a bit.

2023-08-21 11:37 UTC, LemmyMwaura commented on libs/data/sections/src/lib/data-sections.module.ts
> +import { NgModule } from '@angular/core';
There's no need for this file. Our component has no declarations to manage.

2023-08-21 11:37 UTC, LemmyMwaura commented on libs/elements/cards/src/lib/elewa-project-item-card/elewa-project-item-card.component.ts
> +  // Import of the interface
No need for this comment. Only use JsDoc comments to describe properties and methods. This allows us to get some good Intellisense.

2023-08-21 13:47 UTC, jbdura commented
Changes done

2023-08-23 09:38 UTC, LemmyMwaura requested changes
Kindly share an image of the updated design.

2023-08-23 09:38 UTC, LemmyMwaura commented on libs/data/sections/src/lib/ highlighted-projects.data.ts
> +// import { ProjectItem } from "../../models/sections/projects/cards/src";
remove this comment

2023-08-28 07:06 UTC, LemmyMwaura commented
Closing this as it's been resolved in #36

2023-08-28 07:06 UTC, closed without merging