Reusable news item component#11
italanta/elewa-website pull request #87
Opened 2023-08-22 10:51 UTC by kevinkkimutai

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Reference the issue related to this PR as shown below. Every issue has it's own number you can find the issue numbers [here](https://github.com/italanta/italanta-apps/issues).

Fixes #11

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Screenshot (optional)
![Screenshot from 2023-08-22 13-40-46](https://github.com/italanta/elewa-website/assets/117738367/39501715-4a03-4c5b-8936-d59ff7520b3d)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Test A
- [x] Test B

**Test Configuration**: (optional)

- Firmware version:
- Hardware:
- Toolchain:
- SDK:

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2023-08-23 10:22 UTC, LemmyMwaura requested changes

2023-08-23 10:22 UTC, LemmyMwaura commented on libs/elements/cards/src/lib/components/elewa-news-item-card/elewa-news-item-card.component.ts
> +  }
Should be a property representing one item not a list of items

2023-08-23 10:22 UTC, LemmyMwaura commented on libs/features/pages/home/src/lib/features-pages-home.module.ts
This changes should not be pushed. Any component that needs this will import it.

2023-08-25 09:49 UTC, LemmyMwaura commented
Kindly resolve the above

2023-08-28 07:23 UTC, LemmyMwaura commented
The changes left are very minimal but if not resolved by noon, I'll have to go with another PR.

2023-08-28 09:04 UTC, kevinkkimutai commented
made changes sorry for the delay

On Mon, Aug 28, 2023 at 10:23 AM Lemmy ***@***.***> wrote:

> The changes left are very minimal but if not resolved by noon, I'll have
> to go with another PR.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/italanta/elewa-website/pull/87#issuecomment-1695168779>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4CIW75DBO73ZZFTSZHNTJDXXRBQXANCNFSM6AAAAAA3ZW7G64>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-08-28 10:06 UTC, LemmyMwaura requested changes

2023-08-28 10:06 UTC, LemmyMwaura commented on libs/elements/cards/src/lib/components/elewa-news-item-card/elewa-news-item-card.component.html
> +      <!-- list of all news -->
Since it's one item. No need for this loop

2023-08-28 10:06 UTC, LemmyMwaura commented on libs/elements/cards/src/lib/components/elewa-news-item-card/elewa-news-item-card.component.ts
> +  }
This is not needed. Just work with the input item property

2023-08-28 11:39 UTC, kevinkkimutai commented
Done.

On Mon, Aug 28, 2023 at 1:06 PM Lemmy ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In
> libs/elements/cards/src/lib/components/elewa-news-item-card/elewa-news-item-card.component.html
> <https://github.com/italanta/elewa-website/pull/87#discussion_r1307223407>
> :
>
> > +    <ul class="ulist" *ngFor="let news of newsItem">
> +      <!-- list of all news -->
>
> Since it's one item. No need for this loop
> ------------------------------
>
> In
> libs/elements/cards/src/lib/components/elewa-news-item-card/elewa-news-item-card.component.ts
> <https://github.com/italanta/elewa-website/pull/87#discussion_r1307224002>
> :
>
> > +  ngOnInit(): void {
> +    this.newsItem = __highlightedNews;
> +  }
>
> This is not needed. Just work with the input item property
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/italanta/elewa-website/pull/87#pullrequestreview-1597970577>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4CIW7422P4HLFO4BK4BQCDXXRUSJANCNFSM6AAAAAA3ZW7G64>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-08-28 13:04 UTC, LemmyMwaura submitted a review, later dismissed

2023-08-28 13:34 UTC, LemmyMwaura approved these changes

2023-08-28 13:34 UTC, merged